## README for 0x04-csharp-exceptions ##
### A directory within the holbertonschool-csharp repo ###

| File Name | Description |
| --------- | ----------- |
| 0-safe_list_print/ <br> 0-safe_list_print/0-safe_list_print.csproj <br> 0-safe_list_print/0-safe_list_print.cs | **Task: 0. Safe list printing** <br> A method that prints n elements of a list. The class name is `List` with a prototype of `public static int SafePrint(List<int> myList, int n)`, which returns the number of elements actually printed. `n` represents the number of elements to print, but since it could be greater than the amount of elements present, a `try`/`catch` was used. |
| 1-divide_print/ <br> 1-divide_print/1-divide_print.csproj <br> 1-divide_print/1-divide_print.cs | **Task: 1. Integer division** <br> A function that divides 2 integers and prints the result. The class name is `Int` with a prototype of `public static void divide(int a, int b)`. `try` / `catch` / `finally` was used with the result of the division printed under `finally`. |
| 2-divide_lists/ <br> 2-divide_lists/2-divide_lists.csproj <br> 2-divide_lists/2-divide_lists.cs | **Task: 2. Divide lists** <br> A function that divides element by element 2 lists. The class name is `List` with a prototype of `public static List<int> Divide(List<int> list1, List<int> list2, int listLength)`, where `length` can be greater than it actually is, and in which returns a new list of all division results. If 2 elements couldn't be divided, the division result was `0`. If the division couldn't be done, such as dividing by 0, `Cannot divide by zero` was printed. If either list was too short, then `Out of range` was printed. This was done by using a `try`/`catch`. |
| 3-throw_exception/ <br> 3-throw_exception/3-throw_exception.csproj <br> 3-throw_exception/3-throw_exception.cs | **Task: 3. Throw exception** <br> A function that throws an `Exception`. The class name is `Except` with a prototype of `public static void Throw()`. |
| 4-throw_exception_msg/ <br> 4-throw_exception_msg/4-throw_exception_msg.csproj <br> 4-throw_exception_msg/4-throw_exception_msg.cs | **Task: 4. Throw exception with message** <br> A method that throws an `Exception` with a message. The class name is `Except` with a prototype of `public static void ThrowMsg(string msg)`. |
